using UnityEngine;

// Shared animation driver for every character — player, prisoner, enemy, NPC.
//
// Add this to the character root GameObject alongside other character components.
// The Animator lives on the model child (the prefab with the rig).
//
// Parameters expected on the AnimatorController (generated by
// Tools > Valdris > Generate Character Animator Controller):
//   Speed  (Float)   — 0 = idle, >0.1 = walk
//   Cast   (Trigger) — play spell cast animation
//   Hit    (Trigger) — play hit-reaction animation
//   Dead   (Bool)    — true = play death animation (latching, never resets)
[DisallowMultipleComponent]
public class CharacterAnimator : MonoBehaviour
{
    static readonly int SpeedHash = Animator.StringToHash("Speed");
    static readonly int CastHash  = Animator.StringToHash("Cast");
    static readonly int HitHash   = Animator.StringToHash("Hit");
    static readonly int DeadHash  = Animator.StringToHash("Dead");

    Animator _anim;

    void Awake()
    {
        // true = include inactive GameObjects so disabled rigs are still found.
        _anim = GetComponentInChildren<Animator>(true);
        if (_anim == null)
        {
            Debug.LogWarning($"[CharacterAnimator] No Animator found in children of '{name}'. " +
                             "Assign the CharacterAnimator controller to the model's Animator component.");
            return;
        }

        // Root motion from Mixamo Generic clips moves the hip bone in world space,
        // causing the character to sink. Always force it off.
        _anim.applyRootMotion = false;

        if (_anim.runtimeAnimatorController == null)
            Debug.LogWarning($"[CharacterAnimator] Animator on '{_anim.name}' (child of '{name}') " +
                             "has no controller — run Tools > Valdris > Assign Controller to All Synty Characters.");
    }

    // Called every frame with the character's normalised movement speed (0–1).
    public void SetSpeed(float speed)
    {
        if (_anim == null) return;
        _anim.SetFloat(SpeedHash, speed);
    }

    // Call when this character successfully casts a spell.
    public void TriggerCast()
    {
        if (_anim == null) return;
        _anim.SetTrigger(CastHash);
    }

    // Call when this character takes damage (any amount > 0).
    public void TriggerHit()
    {
        if (_anim == null) return;
        _anim.SetTrigger(HitHash);
    }

    // Call when this character's health reaches 0. Latches — does not reset.
    public void TriggerDeath()
    {
        if (_anim == null) return;
        // Re-enable root motion for the death animation only — the fall clip needs
        // to drive the character's position to the ground. It stays enabled so the
        // character holds the final lying pose rather than snapping back to standing.
        _anim.applyRootMotion = true;
        _anim.SetBool(DeadHash, true);
    }

    public bool IsDead => _anim != null && _anim.GetBool(DeadHash);

    // Call after swapping the model child to re-cache the new Animator.
    public void Refresh()
    {
        _anim = GetComponentInChildren<Animator>(true);
        if (_anim != null) _anim.applyRootMotion = false;
    }

    // Places the character directly into the final frame of the death animation
    // without playing the fall — used when restoring a dead NPC from a save.
    //
    // Root motion stays OFF so the animator cannot move the model child transform.
    // The caller applies the saved model-child offset AFTER this returns so the
    // corpse appears at the exact position it was in when saved.
    public void ForceDeadImmediate()
    {
        if (_anim == null) return;
        _anim.applyRootMotion = false;
        _anim.SetBool(DeadHash, true);
        // Advance by a large delta so we skip past any crossfade duration and
        // land well into the death clip's final hold frame. applyRootMotion=false
        // ensures none of this advancement moves the model child's transform.
        _anim.Update(10f);
    }
}
